# ------------------- General Options -------------------------

description                  : AgentFormer (DLow)
results_root_dir             : results
seed                         : 1 
dataset                      : nuscenes_pred
data_root_ethucy             : datasets/eth_ucy
data_root_nuscenes_pred      : datasets/nuscenes_pred
load_map                     : true
map_version                  : 0.1
dynamic_padding              : True
num_workers                  : 12

# ------------------- Feature Extractor -------------------------

batch_size                   : 4
past_frames                  : 4
future_frames                : 12
min_past_frames              : 2
min_future_frames            : 12

max_agent_num                : 20
traj_scale                   : 10
motion_dim                   : 2
forecast_dim                 : 2

# ------------------- Model -------------------------
model_id: dlow
pred_cfg: nuscenes_5sample_dynapad_agentformer_pre
pred_epoch: 100
qnet_mlp: [512, 256]
activation: 'tanh'
dropout: 0.1
share_eps: true
train_w_mean: true
rand_rot_scene: true

# ------------------- Dataset preprocess -------------------------
input_type: ['scene_norm', 'vel', 'heading']
fut_input_type: ['scene_norm', 'vel', 'heading']
dec_input_type: ['scene_norm','heading']
use_map: true

# ------------------- VAE-------------------------

nz                           : 32
sample_k                     : 10

# ------------------- Training Parameters -------------------------

lr                           : 1.e-4
loss_cfg:
  kld:
    weight: 0.1
    min_clip: 10
  diverse:
    weight: 1
    d_scale: 2
  recon:
    weight: 5.0

num_epochs                   : 100
lr_fix_epochs                : 10
lr_scheduler: 'warmup'
warmup_rate: 0.1
decay_step: 5
decay_gamma: 0.5
print_freq                   : 20
model_save_freq              : 5
weight_decay: 0
