# ------------------- General Options -------------------------:

description                  : AgentFormer (Before DLow)
results_root_dir             : results
seed                         : 1
dataset                      : nuscenes_pred
data_root_nuscenes_pred      : datasets/nuscenes_pred
load_map                     : true
map_version                  : 0.1
num_workers                  : 12
dynamic_padding              : True

# ------------------- Feature Extractor -------------------------
batch_size                   : 8
past_frames                  : 4
future_frames                : 12
min_past_frames              : 2
min_future_frames            : 12
max_agent_num                : 20
traj_scale                   : 10
motion_dim                   : 2
forecast_dim                 : 2
conn_dist                    : 1000000.
one_direction_past           : false

# ------------------- Model -------------------------

model_id: agentformer
tf_version: v2
tf_model_dim: 256
tf_ff_dim: 512
tf_nhead: 8
tf_dropout: 0.1
input_type: ['scene_norm', 'vel', 'heading']
fut_input_type: ['scene_norm', 'vel', 'heading']
dec_input_type: ['scene_norm','heading']
context_names: ['agent_maps']
pred_type: 'scene_norm'
sn_out_type: 'norm'
pos_concat: true
rand_rot_scene: true
map_moco: true
moco_num: 50
use_map: true
use_agent_aware: true

agent_maps_encoder:
  model_id: map_cnn
  normalize: true
  hdim: [32, 32, 32, 1]
  kernels: [5, 5, 5, 3]
  strides: [2, 2, 1, 1]
  out_dim: 128
  dropout: 0.1

past_trj_encoder:
  nlayer: 2
  tf_model_dim: 256

future_trj_encoder:
  nlayer: 2
  tf_model_dim: 256

context_encoder:
  nlayer: 2

future_decoder:
  nlayer: 2
  # in_mlp_dim: [512,256]
  out_mlp_dim: [512, 256]
  concat_input: False

future_encoder:
  nlayer: 2
  # in_mlp_dim: [512,256]
  out_mlp_dim: [512, 256]
# ------------------- VAE-------------------------

nz                           : 32
sample_k                     : 5
learn_prior                  : true

# ------------------- Training Parameters -------------------------

lr                           : 1.e-4
loss_cfg:
  mse:
    weight: 1.0
  kld:
    weight: 1.0
    min_clip: 2.0
  sample:
    weight: 1.0
    k: 5
  clip:
    weight: 1
    do: true
    pastenc: false
    pretrain: True
    contrast_objective: ['agent_maps']
    temperature: 0.07
    learn_temperature: True
  moco:
    weight: 1
    temperature: 0.07
    learn_temperature: True

num_epochs                   : 20
lr_fix_epochs                : 10
lr_scheduler: 'warmup'
decay_step: 10
warmup_rate: 0.1
decay_gamma: 0.5
print_freq                   : 20
model_save_freq              : 10
weight_decay: 0

